buildscript {
    repositories {
        google()
        mavenCentral()
        // Appodeal's repository
        maven { url "https://artifactory.appodeal.com/appodeal" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // Appodeal's repository (if needed for subprojects as well)
        maven { url "https://artifactory.appodeal.com/appodeal" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

